services:
  prometheus:
    image: prom/prometheus:latest
    container_name: task_manager_prometheus
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - task_manager_network

  grafana:
    image: grafana/grafana:latest
    container_name: task_manager_grafana
    ports:
      - "3000:3000"
    env_file:
      - ./configs/.env
    networks:
      - task_manager_network
    depends_on:
      - prometheus

  db:
    image: postgres:latest
    container_name: task_manager_db
    hostname: db
    ports:
      - "5555:5432"
    env_file:
      - ./configs/.env
    volumes:
      - ./schemas/000001_init_schema.up.sql:/docker-entrypoint-initdb.d/000001_init_schema.up.sql
      - ./configs./postgresql.conf:/etc/postgresql/postgresql.conf
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - task_manager_network

  app:
    build: .
    container_name: task_manager_app
    depends_on:
      - db
      - prometheus
    restart: always
    ports:
      - "8888:8888"
      - "8889:8889"
    env_file:
      - ./configs/.env
    networks:
      - task_manager_network    

volumes:
  db_data:

networks:
  task_manager_network:
    name: task_manager_network
    driver: bridge 